--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21/07/2022 16:47:04
-- Server version: 8.0.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS platzi_operation;

CREATE DATABASE platzi_operation
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE platzi_operation;

--
-- Create table `operations`
--
CREATE TABLE operations (
  transaction_id int UNSIGNED NOT NULL AUTO_INCREMENT,
  book_id int UNSIGNED NOT NULL,
  client_id int UNSIGNED NOT NULL,
  type enum ('lend', 'sell') NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  finished tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (transaction_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `clients`
--
CREATE TABLE clients (
  client_id int UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  email varchar(100) NOT NULL,
  birthdate datetime DEFAULT NULL,
  gender enum ('M', 'F', 'ND') NOT NULL,
  active tinyint NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `email` on table `clients`
--
ALTER TABLE clients
ADD UNIQUE INDEX email (email);

--
-- Create table `books`
--
CREATE TABLE books (
  book_id int UNSIGNED NOT NULL AUTO_INCREMENT,
  author_id int UNSIGNED DEFAULT NULL,
  title varchar(100) NOT NULL,
  year int UNSIGNED NOT NULL DEFAULT 1900,
  language varchar(2) NOT NULL DEFAULT 'es' COMMENT 'ISO 639-1 Language',
  cover_url varchar(500) DEFAULT NULL,
  price double(6, 2) NOT NULL DEFAULT 10.00,
  sellable tinyint DEFAULT 1,
  copies int NOT NULL DEFAULT 1,
  description text DEFAULT NULL,
  PRIMARY KEY (book_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `authors`
--
CREATE TABLE authors (
  author_id int UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  nationality varchar(3) DEFAULT NULL,
  PRIMARY KEY (author_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table operations
--
-- Table platzi_operation.operations does not contain any data (it is empty)

-- 
-- Dumping data for table clients
--
INSERT INTO clients VALUES
(1, 'Maria Dolores Gomez', 'Maria Dolores.95983222J@random.names', '1971-06-06 00:00:00', 'F', 0, '2018-04-09 16:51:30', '2022-07-18 17:38:56');

-- 
-- Dumping data for table books
--
INSERT INTO books VALUES
(1, 1, 'El Laberinto de la Soledad', 1900, 'es', NULL, 10.00, 1, 1, NULL),
(2, 1, 'Vuelta al laberinto de la Soledad', 1960, 'es', NULL, 10.00, 1, 1, NULL);

-- 
-- Dumping data for table authors
--
INSERT INTO authors VALUES
(1, 'German', 'ARG');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;